### ISSUE TITLE
Skipping cutscenes after dying

### ISSUE THREAD

**Issue by Uarux** [Ajarmar/platinum#2]
When fighting a boss after dying, you can still "skip" the shortened cutscene, which just resets it. That said, skipping immediatedly upon entering is still faster than letting the cutscene play out, so it's a minor inconvenience if anything. But I thought it was worth pointing out.

https://user-images.githubusercontent.com/31782949/107884504-2d79a100-6ed4-11eb-96e0-cc9fe9b28ad2.mp4

**Comment by Ajarmar** [comment]
This is intentional (since, as you say, it's faster to skip even the shortened cutscene). It works the same way in most cases in Zero 3.

That said, the thing that ends up being a bit weird about this is how late you can skip the cutscenes in this hack (but this also applies to longer cutscenes - you can pretty much always skip until the point where you gain control of Zero). Still undecided on whether or not I want to change that, because it's just a minor thing that doesn't matter very much.
